@extends('layouts.admin.app')
@section('title', 'Reports - Tokobii')
@section('content')
<h2 class="fw-bold mb-1">Reports</h2><p class="text-muted mb-4">Pusat laporan penjualan, data toko, dan keluhan produk.</p>
<div class="row g-3 mb-4">@foreach(['sales' => 'Total Sales', 'products' => 'Total Products', 'customers' => 'Total Customers', 'orders' => 'Total Orders', 'reports' => 'Product Reports', 'pending' => 'Pending', 'replied' => 'Replied'] as $key => $label)<div class="col-6 col-md-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">{{ $label }}</small><h4 class="fw-bold mb-0">{{ $key === 'sales' ? 'Rp '.number_format($stats[$key], 0, ',', '.') : $stats[$key] }}</h4></div></div></div>@endforeach</div>
<h4 class="fw-bold">Categories</h4><div class="row g-3 mb-4">@forelse($categories as $category)<div class="col-12 col-md-4"><a href="{{ route('admin.reports.categories.show', $category) }}" class="card border-0 shadow-sm text-decoration-none text-dark h-100"><div class="card-body"><h5 class="fw-bold mb-1">📁 {{ $category->name }}</h5><small class="text-muted">{{ $category->reports_count }} laporan produk</small></div></a></div>@empty<div class="text-muted">Belum ada kategori.</div>@endforelse</div>
<div class="card border-0 shadow-sm"><div class="card-header bg-white py-3"><h4 class="fw-bold mb-0">Semua Product Reports</h4></div><div class="card-body"><form class="row g-2 mb-3"><div class="col-md-3"><select class="form-select" name="category"><option value="">Semua kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('category') == $category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="col-md-3"><select class="form-select" name="product"><option value="">Semua produk</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected(request('product') == $product->id)>{{ $product->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="status"><option value="">Semua status</option>@foreach(['pending','replied','resolved'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-md-3"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Customer, invoice, produk"></div><div class="col-md-1"><button class="btn btn-primary w-100">Filter</button></div></form>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Customer</th><th>Produk / Kategori</th><th>Invoice</th><th>Masalah</th><th>Status</th><th>Dibuat</th><th></th></tr></thead><tbody>@forelse($reports as $report)<tr><td>{{ $report->user->name }}<small class="d-block text-muted">{{ $report->user->email }}</small></td><td>{{ $report->product->name }}<small class="d-block text-muted">{{ $report->product->category->name }}</small></td><td>{{ $report->order->invoice_number }}</td><td>{{ \Illuminate\Support\Str::limit($report->description, 60) }}</td><td><span class="badge {{ $report->status === 'pending' ? 'bg-warning text-dark' : ($report->status === 'resolved' ? 'bg-success' : 'bg-primary') }}">{{ ucfirst($report->status) }}</span></td><td>{{ $report->created_at->format('d M Y') }}</td><td><a href="{{ route('admin.reports.show', $report) }}" class="btn btn-sm btn-outline-primary">Detail</a></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada laporan.</td></tr>@endforelse</tbody></table></div>{{ $reports->links('pagination::bootstrap-5') }}</div></div>
@endsection
